In [ ]:
import numpy as np

In [27]:
a = np.linspace(1, 72, 72)
A = np.array(a).reshape((3, 4, 6))
print(A)

[[[ 1.  2.  3.  4.  5.  6.]
  [ 7.  8.  9. 10. 11. 12.]
  [13. 14. 15. 16. 17. 18.]
  [19. 20. 21. 22. 23. 24.]]

 [[25. 26. 27. 28. 29. 30.]
  [31. 32. 33. 34. 35. 36.]
  [37. 38. 39. 40. 41. 42.]
  [43. 44. 45. 46. 47. 48.]]

 [[49. 50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59. 60.]
  [61. 62. 63. 64. 65. 66.]
  [67. 68. 69. 70. 71. 72.]]]


In [28]:
A[1, 2, 3] #  即 A[1][2][3]

40.0

In [30]:
A[1:3, 1:3, 1:4]

array([[[32., 33., 34.],
        [38., 39., 40.]],

       [[56., 57., 58.],
        [62., 63., 64.]]])

In [32]:
A[:, 1:3, 1:4]

array([[[ 8.,  9., 10.],
        [14., 15., 16.]],

       [[32., 33., 34.],
        [38., 39., 40.]],

       [[56., 57., 58.],
        [62., 63., 64.]]])

In [37]:
A[:, :, 4:6]

array([[[ 5.,  6.],
        [11., 12.],
        [17., 18.],
        [23., 24.]],

       [[29., 30.],
        [35., 36.],
        [41., 42.],
        [47., 48.]],

       [[53., 54.],
        [59., 60.],
        [65., 66.],
        [71., 72.]]])

In [36]:
A[:, :, 5] # 只取最后一列

array([[ 6., 12., 18., 24.],
       [30., 36., 42., 48.],
       [54., 60., 66., 72.]])

In [40]:
A[...,5]

array([[ 6., 12., 18., 24.],
       [30., 36., 42., 48.],
       [54., 60., 66., 72.]])

In [41]:
A[-1,]

array([[49., 50., 51., 52., 53., 54.],
       [55., 56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65., 66.],
       [67., 68., 69., 70., 71., 72.]])

In [38]:
A[1, :, :] # 只取第一行

array([[25., 26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35., 36.],
       [37., 38., 39., 40., 41., 42.],
       [43., 44., 45., 46., 47., 48.]])

##### 正数数组索引：指定获取数组中某一位置的元素

In [57]:
A[1:2]

array([[[25., 26., 27., 28., 29., 30.],
        [31., 32., 33., 34., 35., 36.],
        [37., 38., 39., 40., 41., 42.],
        [43., 44., 45., 46., 47., 48.]]])

In [49]:
A[1:2, [0, 3]] # 从 A[1, 2] 中取出第 0 行 和第 3 行

array([[[25., 26., 27., 28., 29., 30.],
        [43., 44., 45., 46., 47., 48.]]])

In [53]:
A[1:2, [0, 3], [2, 4]] # 从 A[1, 2] 中取（0，2）（3，4）位置处的元素

array([[27., 47.]])

In [56]:
A[[1, 2],[0, 3],[2, 4]] # 从 A 中取（1，0，2）（2，3，4）位置处的元素

array([27., 71.])

##### 布尔索引

In [58]:
A

array([[[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.],
        [19., 20., 21., 22., 23., 24.]],

       [[25., 26., 27., 28., 29., 30.],
        [31., 32., 33., 34., 35., 36.],
        [37., 38., 39., 40., 41., 42.],
        [43., 44., 45., 46., 47., 48.]],

       [[49., 50., 51., 52., 53., 54.],
        [55., 56., 57., 58., 59., 60.],
        [61., 62., 63., 64., 65., 66.],
        [67., 68., 69., 70., 71., 72.]]])

In [67]:
A[A % 3 == 0]

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39.,
       42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72.])

In [77]:
A[A > 30] # 大于 30 的元素

array([31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55., 56.,
       57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
       70., 71., 72.])

In [76]:
A[A > 30][A[A > 30] < 50] # 大于 30 小于 50 的元素

array([31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45., 46., 47., 48., 49.])

##### 保留满足指定条件的行
https://www.cnblogs.com/qiu-hua/p/7808896.html

In [86]:
A[A[:, :, 4] % 5 == 0,:] # 保留第四列（从零开始数）能被 5 整处的行

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [31., 32., 33., 34., 35., 36.],
       [61., 62., 63., 64., 65., 66.]])

In [88]:
# ~ 取补运算符
A[~(A[:, :, 4] % 5 == 0),:] # 保留第四列（从零开始数）不能被 5 整处的行

array([[ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30.],
       [37., 38., 39., 40., 41., 42.],
       [43., 44., 45., 46., 47., 48.],
       [49., 50., 51., 52., 53., 54.],
       [55., 56., 57., 58., 59., 60.],
       [67., 68., 69., 70., 71., 72.]])

##### 花式索引, 跟上面的正数索引差不多

In [93]:
A[[0, 2]] # 第 0 行 和 第 2 行

array([[[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.],
        [19., 20., 21., 22., 23., 24.]],

       [[49., 50., 51., 52., 53., 54.],
        [55., 56., 57., 58., 59., 60.],
        [61., 62., 63., 64., 65., 66.],
        [67., 68., 69., 70., 71., 72.]]])

In [105]:
A[0, 2] # 第 （0,2）位置


array([13., 14., 15., 16., 17., 18.])